sudo: false
language: python
matrix:
  fast_finish: true
  include:
  - python: 3.4.2
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.6'
    env: TOXENV=flake8
  - python: '3.6'
    env: TOXENV=pylint

install: pip install -U tox coveralls
script: tox
after_success: coveralls
