#!/bin/bash
set -eu
# simple script to run the integration tests using a Xiaomi miflora device
# 
# - tests need to run as root so we can scan for new devices
# - store the mac address of the Miflora device you're using in a file
#   called ".test_mac" so you can run the test with one call.

MAC=`cat .test_mac` 

if [ $# -eq 0 ]; then
    SUITE=test/integration_tests
else
    SUITE=$1
fi
TOX=$(which tox)

# run tox with sudo to be able to scan for devices
# run in separate folder so avoid later issues on file permissions
sudo ${TOX} -e integration_tests --workdir=.tox_sudo -- --mac=$MAC $SUITE

# reset permissions after running as root
sudo chown -R $USER * .*